---
title: "Thermal time"
author: "Sara DeLaurentis"
date: "2/1/2022"
output: html_document
purpose: tabulate (and plot?) thermal time for Itasca Project
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stringi)
library(stringr)
library(dplyr)
library(ggplot2)
library(purrr)

library(nlme)
library(car)



```

## R Markdown


```{r }

#for one file testing
temps <- read.csv("C2A_R3_m0surf_i39_2020.csv")
head(temps)
temps$longdate <- as.POSIXct(temps$longdate)


#for multiple file testing (4 or more files merged together)

csv_files <- list.files(pattern = ".csv", full.names = TRUE)
head(csv_files)

merged_ibuttons <- map_dfr(csv_files, read.csv) #map_dfr reads csv files and joins them by rowbind.
head(merged_ibuttons)
str(merged_ibuttons)

temps <- merged_ibuttons

#write.csv(merged_ibuttons, file = "merged_ibuttons.csv")


str(temps)

View(temps)



temps <- temps %>% 
  group_by(labels, longdate) %>% #groups by label and longdate. this keeps all the ibuttons separate during this process.
  mutate(daily_avg = mean(value)) %>%  #create daily_avg column
  distinct(longdate, .keep_all = TRUE) %>% #only keep distinct longdate rows (for each ibutton label group)
  ungroup() 
head(temps)



plot(daily_avg ~ longdate, data = temps)
#developing thermal time code section

#sum(df$column == value, na.rm=TRUE)

sum(temps$value >= 0, na.rm=TRUE)



```

##Linear model practice


```{r }


fm1 <- lm(daily_avg ~ longdate, data = temps) #daily avg as a function of date
summary(fm1) 
plot(daily_avg ~ longdate, data = temps)
lines(fitted.values(fm1))
residualPlot(fm1)

durbinWatsonTest(fm1)



fm2 <- lm(daily_avg ~ treatment * as.Date(longdate), data = temps)

#data set as of 2/2/2022, 10pm. All the same depth, sites C2B and C5A, R1 and R2 at each: 
#"./C2B_R1_m0surf_i105_2020.csv" 
#"./C2B_R2_m0surf_i101_2020.csv" 
#"./C5A_R1_m0surf_i16_2020.csv"  
#"./C5A_R2_m0surf_i21_2020.csv"

summary(fm2)
anova(fm2)

residualPlot(fm2)

durbinWatsonTest(fm2)


fm3 <- lme(daily_avg ~ treatment * julian(as.Date(longdate)), data = temps, random = ~ 1 | treatment)

julian(as.Date("1970-04-12"))


summary(fm3)
#residualPlot(fm3)
#durbinWatsonTest(fm3)

AIC(fm3)

```


```{r }



```
